### ISSUE TITLE
Owner Meta motionY is not 0 while player doesn't move in the Y axis

### ISSUE THREAD

**Issue by Ale32bit** [SwitchCraftCC/Plethora-Fabric#53] opened 2023-05-01 16:35 UTC
The `motionY` variable of the owner meta should be 0 if the player doesn't move in the Y axis, but instead it has this value: `-0.07840000152587890680511151231257827021181583404541015625`.

**Comment by Lemmmy** [comment] 2023-05-01 16:36
Duplicate of #52

**Closed as completed by Lemmmy** 2023-05-01 16:36 UTC
Labels: duplicate

**Comment by Ale32bit** [comment] 2023-05-01 16:38
This looks like a different problem but correlated to it.
Are you sure?

**Comment by Lemmmy** [comment] 2023-05-01 16:38
Yes. It's the wrong velocity object entirely.
