### ISSUE TITLE
[Suggestion] Keyboard capture

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/Plethora-Fabric#35] opened 2023-02-20 18:08 UTC
New Keyboard module method:
`neural.captureKeyboard()`
This would pop up the screen that sends all kb input to the neural as if you right clicked it in the air
It could be useful for overlay glasses text input as it will stop MC keybinds from taking effect.
It would also send an event `KeyboardClosed` upon you pressing ESC to close the Screen

**Comment by Kan18** [comment] 2023-02-20 18:12
Alternatively, just implement old Plethora's behavior, where right-clicking an unbound keyboard would open a keyboard that sent input to the neural. 1.12 Plethora also included events for mouse positions if the neural had overlay glasses (glasses_click, glasses_up, glasses_scroll, and glasses_drag)

**Comment by scmcgowen** [comment] 2023-02-20 18:14
I was thinking both in combination
I didn't even know that feature wasn't implemented.

Its a gripe I had with 1.12.2 plethora too though that I couldn't open that GUI with it as a module in code

**Comment by Kan18** [comment] 2023-02-20 18:22
it seems this omission was intentional
<img width="491" alt="image" src="https://user-images.githubusercontent.com/24967425/220177412-7755b49b-d14e-4721-8627-a1d6561865ba.png">

**Comment by Lemmmy** [comment] 2023-02-20 18:25
> 1.12 Plethora also included events for mouse positions if the neural had overlay glasses (glasses_click, glasses_up, glasses_scroll, and glasses_drag)

Duplicate of #12. The ommission of the rest of the behavior is intentional.

**Closed as not planned by Lemmmy** 2023-02-20 18:25 UTC
Labels: duplicate, wontfix
